### ISSUE TITLE
node-gyp build failed

### ISSUE THREAD

**Issue by setoelkahfi** [Paxa/postbird#22]
```
> libpq@1.8.7 install /Users/me/path/postbird/node_modules/libpq
> node-gyp rebuild

/bin/sh: pg_config: command not found
gyp: Call to 'pg_config --libdir' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/me/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/me/.nvm/versions/node/v9.3.0/bin/node" "/Users/me/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users//me/path/postbird/node_modules/libpq
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libpq@1.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.8.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2017-12-15T09_56_51_775Z-debug.log
```

Node 9.3.0
Npm 5.6.0

Do you know what's wrong with this?

**Comment by Paxa** [comment]
Compiling script for libpq can not find `pg_config`.
If you using Postgres.app, then can try:

```
PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin/ npm install
```

Or can make more permanent changes:
Add to `~/.bashrc` or `~/.zshrc`
```
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
```
^ this will also make postgres commands easier to use, e.g. `psql`, `pg_dump` etc

**Comment by setoelkahfi** [comment]
Thanks for the response. I'll try.

**Comment by Paxa** [comment]
Thank you, pushed better documentation 9a709c0
