### ISSUE TITLE
NODE_MODULE_VERSION error

### ISSUE THREAD

**Issue by setoelkahfi** [Paxa/postbird#23]
When `./run`, I get this:
```
ERROR error:  Error: The module '/Users/john/postbird/node_modules/libpq/build/Release/addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
INFO Error: The module '/Users/john/postbird/node_modules/libpq/build/Release/addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/john/postbird/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/john/postbird/node_modules/libpq/index.js:1:201)

```
I removed libpq folder and do `npm rebuild` and `npm install` but not solved the problem. 

What's the possible workaround for this? 
I guess it has something to do with node version. I'm not sure.

node v9.3.0
npm 5.6.0

**Comment by Paxa** [comment]
Try:
```
PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin ./node_modules/.bin/electron-rebuild -n 54
```

or `rake rebuild_ext`

Sorry for confusion, native extensions should be compiled for electron version

**Comment by setoelkahfi** [comment]
OK, solved. 
I'm exploring now.

**Comment by Paxa** [comment]
Thank you, pushed better documentation 9a709c0
